export interface Post {
  slug: string;
  title: string;
  summary: string;
  date: string;
  tags: string[];
  readTime: number;
  content: string;
}

const BACKTICK = '`';

function code(lang: string, ...lines: string[]): string {
  return `${BACKTICK}${lang}\n${lines.join('\n')}\n${BACKTICK}`;
}

export const posts: Post[] = [
  {
    slug: "hello-world",
    title: "Hello World — 重新出发",
    summary: "一个关于重新定义个人的故事。告别庞大的平台项目，回归纯粹的技术博客。",
    date: "2026-06-04",
    tags: ["随笔", "技术"],
    readTime: 3,
    content: [
      "# Hello World — 重新出发",
      "",
      "> Welcome to the new era.",
      "",
      "## 为什么重写？",
      "",
      "之前的项目太庞大了。登录、注册、社交、数据中台…… 想法很多，但真正想做的只是**写点东西**。",
      "",
      "所以这次，一切从简。",
      "",
      "## 这个站点要做什么？",
      "",
      "- 写技术笔记",
      "- 记录想法",
      "- 分享踩坑经验",
      "- 偶尔写点乱七八糟的东西",
      "",
      "就这么简单。",
      "",
      "## 技术栈",
      "",
      "- **Next.js 14** — 前端框架",
      "- **Tailwind CSS** — 样式",
      "- **TypeScript** — 类型安全",
      "- **Cyberpunk** — 风格",
      "",
      "## 写在最后",
      "",
      "代码不只是代码。",
      "",
      "希望这个小小的站点，能成为一个干净的起点。",
      "",
      "---",
      "*发表于 2026-06-04*",
    ].join('\n'),
  },
  {
    slug: "neon-terminal-guide",
    title: "搭建赛博朋克风格的开发终端",
    summary: "用 Windows Terminal + PowerShell + Oh-My-Posh 打造霓虹色终端。",
    date: "2026-06-03",
    tags: ["工具", "终端"],
    readTime: 5,
    content: [
      "# 搭建赛博朋克风格的开发终端",
      "",
      "> 你的终端，就是你的脸面。",
      "",
      "## 为什么要自定义终端？",
      "",
      "每天花 8 小时面对终端，一个好看的终端能让人心情愉悦。",
      "",
      "## 方案概览",
      "",
      "- **终端模拟器**: Windows Terminal",
      "- **Shell**: PowerShell 7+",
      "- **提示符美化**: Oh-My-Posh",
      "- **字体**: Fira Code",
      "",
      "## 安装步骤",
      "",
      "### 1. 安装 Windows Terminal",
      "",
      code("", "winget install Microsoft.WindowsTerminal"),
      "",
      "### 2. 安装 PowerShell 7",
      "",
      code("", "winget install PowerShell"),
      "",
      "### 3. 安装 Oh-My-Posh",
      "",
      code("", "winget install JanDeDobbeleer.OhMyPosh"),
      "",
      "### 4. 配置提示符",
      "",
      "编辑 `$PROFILE` 文件：",
      "",
      code("powershell",
        "oh-my-posh init pwsh --config \"C:\\Users\\YourName\\.config\\posh\\cyber.omp.json\" | Invoke-Expression",
      ),
      "",
      "## 配色方案",
      "",
      "推荐霓虹配色：",
      "- 背景: `#0a0a0a`",
      "- 主色: `#00f0ff` (青色)",
      "- 强调: `#a855f7` (紫色)",
      "- 警告: `#ff006e` (粉色)",
      "",
      "---",
      "*发表于 2026-06-03*",
    ].join('\n'),
  },
  {
    slug: "nextjs-performance",
    title: "Next.js 14 性能优化笔记",
    summary: "在实践中总结的 Next.js 性能优化技巧，从首屏到构建。",
    date: "2026-06-01",
    tags: ["Next.js", "性能"],
    readTime: 8,
    content: [
      "# Next.js 14 性能优化笔记",
      "",
      "> 性能优化不是一门玄学，而是一门工程。",
      "",
      "## 优化清单",
      "",
      "### 1. 图片优化",
      "",
      "使用 \`next/image\`，设置合适的 \`sizes\` 属性。",
      "",
      "### 2. 字体优化",
      "",
      "使用 \`next/font\` 避免布局偏移。",
      "",
      "### 3. 代码分割",
      "",
      "动态导入非关键组件。",
      "",
      "### 4. HTTP 缓存",
      "",
      "在 \`next.config.ts\` 中配置包导入优化。",
      "",
      "## 测试",
      "",
      "使用 \`next lint\` 检查代码质量，用 Chrome DevTools 的 Lighthouse 测性能评分。",
      "",
      "---",
      "*发表于 2026-06-01*",
    ].join('\n'),
  },
  {
    slug: "typescript-tips",
    title: "TypeScript 实用技巧 10 条",
    summary: "日常开发中积累的 TypeScript 小技巧，提升代码质量。",
    date: "2026-05-28",
    tags: ["TypeScript", "技巧"],
    readTime: 6,
    content: [
      "# TypeScript 实用技巧 10 条",
      "",
      "> 好的类型声明是最好的文档。",
      "",
      "## 1. 使用 \`satisfies\` 操作符",
      "",
      "让 TS 推断类型，同时做类型检查。",
      "",
      "## 2. 推断函数返回值",
      "",
      "使用模板字符串类型。",
      "",
      "## 3. 使用 \`Partial\` 和 \`Pick\`",
      "",
      "组合工具类型，打造灵活的接口。",
      "",
      "## 4. 空值合并 vs 逻辑或",
      "",
      "推荐用 \`??\` 替代 \`||\`，更精确地处理 falsy 值。",
      "",
      "---",
      "*发表于 2026-05-28*",
    ].join('\n'),
  },
];

export function getPostBySlug(slug: string): Post | undefined {
  return posts.find((p) => p.slug === slug);
}

export function getPostSlugs(): string[] {
  return posts.map((p) => p.slug);
}
