import { create } from 'zustand'
import { persist, createJSONStorage } from 'zustand/middleware'

export type Language = 'zh' | 'en'

interface LanguageState {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

// 中文翻译
const zhTranslations: Record<string, string> = {
  'common.continueWithGithub': '继续使用 GitHub',
  'common.orContinueWithEmail': '或继续使用邮箱',
  'login.title': '身份验证',
  'login.subtitle': '安全访问您的 NebulaHub 工作区',
  'login.systemLabel': 'SYS.AUTH // ONLINE',
  'login.uplinkEstablished': 'UPLINK_ESTABLISHED_',
  'login.nebulaHubSSO': '[ NebulaHub SSO ]',
  'login.version': 'V03.01 // BUILD_2026',
  'login.newToNebulaHub': '新到 NebulaHub？',
  'login.createAccount': '创建账户',
  'login.forgotPassword': '忘记密码？',
  'login.remembered': '已有账户？',
  'login.signIn': '登录',
  'login.errorPasswordMismatch': '密码不匹配',
  'login.errorLoginFailed': '登录失败',
  'login.errorNetworkError': '网络错误，请重试',
  'login.successLogin': '登录成功',
  'login.welcomeBack': '欢迎回来！正在跳转...',
  'login.githubLoginFailed': 'GitHub 登录失败',
  'login.usernameMin3': '用户名至少 3 个字符',
  'login.passwordMin6': '密码至少 6 个字符',
  'login.passwordMatch': '密码匹配',
  'login.username': '用户名',
  'login.email': '邮箱',
  'login.password': '密码',
  'login.confirmPassword': '确认密码',
  'login.loginButton': '初始化连接',
  'register.title': '初始化访问权限',
  'register.subtitle': '注册并接入 NebulaHub 协作网络',
  'register.systemLabel': 'SYS.REGISTER // ACTIVE',
  'register.uplinkEstablished': 'NEW_USER_PROVISIONING_',
  'register.nebulaId': '[ NEBULA.ID ]',
  'register.version': 'V03.01 // BUILD_2026',
  'register.alreadyHaveAccount': '已有账户？',
  'register.signIn': '登录',
  'register.continueWithGithub': '继续使用 GitHub',
  'register.orContinueWithEmail': '或继续使用邮箱',
  'register.usernameMin3': '用户名至少 3 个字符',
  'register.passwordMin6': '密码至少 6 个字符',
  'register.passwordMatch': '密码匹配',
  'register.successRegister': '注册成功',
  'register.welcomeToNebulaHub': '欢迎加入 NebulaHub！正在跳转...',
  'register.registerFailed': '注册失败',
  'register.githubRegisterFailed': 'GitHub 注册失败',
  'register.networkError': '网络错误，请重试',
  'register.passwordMismatch': '两次输入的密码不一致',
  'register.usernameTooShort': '用户名太短',
  'register.passwordTooShort': '密码太短',
  'register.username': '用户名',
  'register.email': '邮箱',
  'register.password': '密码',
  'register.confirmPassword': '确认密码',
  'register.registerButton': '初始化账户',
  'forgotPassword.title': '重置密码',
  'forgotPassword.subtitle': '恢复账户访问权限',
  'forgotPassword.systemLabel': 'SYS.RESET // ACTIVE',
  'forgotPassword.uplinkEstablished': 'PASSWORD_RESET_PENDING',
  'forgotPassword.nebulaAuth': '[ NEBULA.AUTH ]',
  'forgotPassword.version': 'V03.01 // BUILD_2026',
  'forgotPassword.email': '邮箱',
  'forgotPassword.sendResetLink': '发送重置链接',
  'forgotPassword.backToLogin': '返回登录',
  'forgotPassword.successEmailSent': '重置邮件已发送',
  'forgotPassword.checkEmail': '请检查您的邮箱，点击邮件中的链接重置密码',
  'forgotPassword.errorFailed': '发送失败，请重试',
  'forgotPassword.errorNetworkError': '网络错误，请重试',
  'language.zh': '中文',
  'language.en': 'English',
  'language.switchTo': '切换语言',
}

// 英文翻译
const enTranslations: Record<string, string> = {
  'common.continueWithGithub': 'Continue with GitHub',
  'common.orContinueWithEmail': 'Or continue with email',
  'login.title': 'Authenticate',
  'login.subtitle': 'Secure access to your NebulaHub workspace',
  'login.systemLabel': 'SYS.AUTH // ONLINE',
  'login.uplinkEstablished': 'UPLINK_ESTABLISHED_',
  'login.nebulaHubSSO': '[ NebulaHub SSO ]',
  'login.version': 'V03.01 // BUILD_2026',
  'login.newToNebulaHub': 'New to NebulaHub?',
  'login.createAccount': 'Create account',
  'login.forgotPassword': 'Forgot password?',
  'login.remembered': 'Already have an account?',
  'login.signIn': 'Sign in',
  'login.errorPasswordMismatch': 'Password mismatch',
  'login.errorLoginFailed': 'Login failed',
  'login.errorNetworkError': 'Network error, please try again',
  'login.successLogin': 'Login successful',
  'login.welcomeBack': 'Welcome back! Redirecting...',
  'login.githubLoginFailed': 'GitHub login failed',
  'login.usernameMin3': 'Username must be at least 3 characters',
  'login.passwordMin6': 'Password must be at least 6 characters',
  'login.passwordMatch': 'Passwords match',
  'login.username': 'USERNAME',
  'login.email': 'IDENTIFIER',
  'login.password': 'PASSCODE',
  'login.confirmPassword': 'CONFIRM_PASSCODE',
  'login.loginButton': 'Initialize Uplink',
  'register.title': 'Initialize Access',
  'register.subtitle': 'Join the NebulaHub collaborative network',
  'register.systemLabel': 'SYS.REGISTER // ACTIVE',
  'register.uplinkEstablished': 'NEW_USER_PROVISIONING_',
  'register.nebulaId': '[ NEBULA.ID ]',
  'register.version': 'V03.01 // BUILD_2026',
  'register.alreadyHaveAccount': 'Already have an account?',
  'register.signIn': 'Sign in',
  'register.continueWithGithub': 'Continue with GitHub',
  'register.orContinueWithEmail': 'Or register with email',
  'register.usernameMin3': 'Username must be at least 3 characters',
  'register.passwordMin6': 'Password must be at least 6 characters',
  'register.passwordMatch': 'Passwords match',
  'register.successRegister': 'Registration successful',
  'register.welcomeToNebulaHub': 'Welcome to NebulaHub! Redirecting...',
  'register.registerFailed': 'Registration failed',
  'register.githubRegisterFailed': 'GitHub registration failed',
  'register.networkError': 'Network error, please try again',
  'register.passwordMismatch': 'Passwords do not match',
  'register.usernameTooShort': 'Username is too short',
  'register.passwordTooShort': 'Password is too short',
  'register.username': 'USERNAME',
  'register.email': 'IDENTIFIER',
  'register.password': 'PASSCODE',
  'register.confirmPassword': 'CONFIRM_PASSCODE',
  'register.registerButton': 'Initialize Account',
  'forgotPassword.title': 'Reset Password',
  'forgotPassword.subtitle': 'Recover access to your account',
  'forgotPassword.systemLabel': 'SYS.RESET // ACTIVE',
  'forgotPassword.uplinkEstablished': 'PASSWORD_RESET_PENDING',
  'forgotPassword.nebulaAuth': '[ NEBULA.AUTH ]',
  'forgotPassword.version': 'V03.01 // BUILD_2026',
  'forgotPassword.email': 'IDENTIFIER',
  'forgotPassword.sendResetLink': 'Send Reset Link',
  'forgotPassword.backToLogin': 'Back to Login',
  'forgotPassword.successEmailSent': 'Reset email sent',
  'forgotPassword.checkEmail': 'Please check your email and click the link to reset your password',
  'forgotPassword.errorFailed': 'Failed to send, please try again',
  'forgotPassword.errorNetworkError': 'Network error, please try again',
  'language.zh': '中文',
  'language.en': 'English',
  'language.switchTo': 'Switch Language',
}

export const useLanguage = create<LanguageState>()(
  persist(
    (set, get) => ({
      language: 'zh',
      setLanguage: (lang) => set({ language: lang }),
      t: (key: string): string => {
        const { language } = get()
        const translations = language === 'zh' ? zhTranslations : enTranslations
        return translations[key] || key
      },
    }),
    {
      name: 'language-storage',
      storage: createJSONStorage(() => localStorage),
    }
  )
)
